/**
 * Write a description of class EventType here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public enum EventType  
{
    KEYPRESS_BUTTON_1, KEYPRESS_BUTTON_2, KEYPRESS_BUTTON_3, KEYPRESS_BUTTON_4, 
    KEYPRESS_BUTTON_5, KEYPRESS_BUTTON_6, KEYPRESS_BUTTON_7, KEYPRESS_BUTTON_8, 
    KEYPRESS_NUMPAD_1, KEYPRESS_NUMPAD_2, KEYPRESS_NUMPAD_3, KEYPRESS_NUMPAD_4, 
    KEYPRESS_NUMPAD_5, KEYPRESS_NUMPAD_6, KEYPRESS_NUMPAD_7, KEYPRESS_NUMPAD_8, 
    KEYPRESS_NUMPAD_9, KEYPRESS_NUMPAD_0, KEYPRESS_NUMPAD_BACK_SPACE, CARD_SWIPED, 
    FUEL_PUMP_START, FUEL_PUMP_END
}
